---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install RDO package
  yum:
    pkg: "{{ rdo_package }}"
    state: "present"
  register: install_cloud_rdo_package
  until: install_cloud_rdo_package | success
  retries: 5
  delay: 2

- name: Install neutron yum dependencies
  yum:
    pkg: "{{ item }}"
    state: "{{ neutron_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ neutron_distro_packages }}"

- name: Install yum packages for LXB
  yum:
    pkg: "{{ item }}"
    state: "{{ neutron_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ neutron_lxb_distro_packages }}"
  when:
    - neutron_services['neutron-linuxbridge-agent']['group'] in group_names
    - neutron_services['neutron-linuxbridge-agent'].service_en | bool

- name: Install yum packages for OVS
  yum:
    pkg: "{{ item }}"
    state: "{{ neutron_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ neutron_ovs_distro_packages }}"
  when:
    - neutron_services['neutron-openvswitch-agent']['group'] in group_names
    - neutron_services['neutron-openvswitch-agent'].service_en | bool

- name: Install yum packages for LBaaS
  yum:
    pkg: "{{ item }}"
    state: "{{ neutron_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ neutron_lbaas_distro_packages }}"
  when:
    - neutron_services['neutron-lbaasv2-agent']['group'] in group_names
    - neutron_lbaasv2 | bool

- name: Install yum packages for VPNaaS
  yum:
    pkg: "{{ item }}"
    state: "{{ neutron_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ neutron_vpnaas_distro_packages }}"
  when:
    - neutron_services['neutron-vpnaas-agent']['group'] in group_names
    - neutron_vpnaas | bool

